import { StyleSheet } from "react-native";

import { colors } from "@/src/theme";

/** Shared typography, layout and surface styles used across screens. */
export const shared = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.surface },
  eyebrow: { color: colors.brand, fontSize: 11, fontWeight: "800", letterSpacing: 1.4, marginTop: 18, marginBottom: 8 },
  screenTitle: { color: colors.onSurface, fontSize: 26, fontWeight: "800", letterSpacing: -0.6 },
  sectionTitle: { color: colors.onSurface, fontSize: 18, fontWeight: "800" },
  cardTitle: { color: colors.onSurface, fontSize: 14, fontWeight: "800" },
  mutedText: { color: colors.onSurfaceSecondary, fontSize: 13, lineHeight: 19 },
  brandText: { color: colors.brand },
  fieldLabel: { color: colors.onSurfaceTertiary, fontSize: 12, fontWeight: "700" },
  input: {
    minHeight: 48,
    backgroundColor: colors.surfaceTertiary,
    color: colors.onSurface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 14,
    fontSize: 15,
  },
  card: {
    marginHorizontal: 18,
    padding: 16,
    borderRadius: 20,
    backgroundColor: colors.surfaceSecondary,
    borderColor: colors.border,
    borderWidth: 1,
    gap: 14,
  },
  topBar: { paddingHorizontal: 18, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  iconButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 14,
    backgroundColor: colors.surfaceSecondary,
    borderColor: colors.border,
    borderWidth: 1,
  },
  iconTile: {
    width: 42,
    height: 42,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.brandTertiary,
  },
  greetingRow: {
    paddingHorizontal: 18,
    marginTop: 20,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  sectionHeading: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    marginBottom: 12,
  },
  segmentRow: { flexDirection: "row", gap: 7 },
  segment: {
    flex: 1,
    minHeight: 38,
    paddingHorizontal: 8,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    backgroundColor: colors.surfaceTertiary,
    borderColor: colors.border,
    borderWidth: 1,
  },
  segmentActive: { backgroundColor: colors.brand, borderColor: colors.brand },
  segmentText: { color: colors.onSurfaceSecondary, fontSize: 11, fontWeight: "700", textTransform: "capitalize" },
  segmentTextActive: { color: colors.onBrandPrimary },
  emptyCard: {
    marginHorizontal: 18,
    padding: 30,
    alignItems: "center",
    gap: 7,
    backgroundColor: colors.surfaceSecondary,
    borderRadius: 18,
    borderColor: colors.border,
    borderWidth: 1,
  },
  rowCenter: { flexDirection: "row", alignItems: "center", gap: 4 },
  smallStrong: { color: colors.onSurfaceSecondary, fontSize: 11, fontWeight: "800" },
  routeText: { color: colors.onSurface, fontSize: 13, fontWeight: "700" },
  totalText: { color: colors.brand, fontSize: 18, fontWeight: "900", marginTop: 3 },
  pressed: { opacity: 0.65, transform: [{ scale: 0.985 }] },
  flex: { flex: 1 },
});
